version: 2

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/node:14.16.1
    steps:
      - checkout
      - run: npm install
      - run: npm test
